Repository SwevenSoftware/BlockCOVID-android, pull requests merged in 2021-06, with the labels that each got.

#57 test per cleaner e reservation
  app/src/test/java/com/sweven/blockcovid/data/repositories/CleanRoomRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/CleanerRoomsRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/EditReservationRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/EndReservationRepositoryTest.kt
Labels: enhancement

#60 removed untestable files from coverage
  app/build.gradle
Labels: refactor

#61 done testing viewmodels
  app/build.gradle
  app/src/test/java/com/sweven/blockcovid/ui/cleanerRooms/CleanerRoomsViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/customReservation/CustomReservationViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/editReservation/EditReservationViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/home/HomeViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/reservation/ReservationViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/roomView/RoomViewViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/userReservartions/UserReservationsViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/userRooms/UserRoomsViewModelTest.kt
  build.gradle
Labels: enhancement

#63 increased branch coverage
  app/build.gradle
  app/src/test/java/com/sweven/blockcovid/data/repositories/CleanerRoomsRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/DeskInfoRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/DeskReservationRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/DeskStatusRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/RoomViewRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/UserReservationRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/data/repositories/UserRoomsRepositoryTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/customReservation/CustomReservationViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/editReservation/EditReservationViewModelTest.kt
  app/src/test/java/com/sweven/blockcovid/ui/roomView/RoomViewViewModelTest.kt
Labels: improvement
