Repository SwevenSoftware/BlockCOVID-android, pull requests merged in 2021-03, with the labels that each got.

#20 Italian UI (switchable to english where possible) refactor
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_help.xml
  app/src/main/res/layout/fragment_prenotazioni.xml
  app/src/main/res/layout/fragment_scanner.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_stanza1.xml
  app/src/main/res/layout/fragment_stanza2.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: improvement

#22 Feature/https
  app/build.gradle
  app/src/main/java/com/sweven/blockcovid/services/NetworkClient.kt
  app/src/main/java/com/sweven/blockcovid/services/OkHttpClient.kt
  app/src/main/res/raw/crt.pem
  app/src/main/res/raw/key.pem
  app/src/main/res/raw/sweven.p12
Labels: improvement

#23 Feature/json requests
  app/src/main/java/com/sweven/blockcovid/data/LoginRepository.kt
  app/src/main/java/com/sweven/blockcovid/services/APIUser.kt
  app/src/main/java/com/sweven/blockcovid/services/NetworkClient.kt
  app/src/main/java/com/sweven/blockcovid/services/OkHttpClient.kt
Labels: refactor

#24 Feature/token expiring
  app/build.gradle
  app/src/main/java/com/sweven/blockcovid/MainActivity.kt
  app/src/main/java/com/sweven/blockcovid/StartActivity.kt
  app/src/main/java/com/sweven/blockcovid/data/LoginDataSource.kt
  app/src/main/java/com/sweven/blockcovid/data/LoginRepository.kt
  app/src/main/java/com/sweven/blockcovid/data/model/LoggedInUser.kt
  app/src/main/java/com/sweven/blockcovid/services/APIUser.kt
  app/src/main/java/com/sweven/blockcovid/services/NetworkClient.kt
  app/src/main/java/com/sweven/blockcovid/services/gsonReceive/Token.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoggedInUserView.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoginActivity.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoginViewModel.kt
  build.gradle
Labels: improvement

#25 Feature/exceptions
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sweven/blockcovid/MainActivity.kt
  app/src/main/java/com/sweven/blockcovid/data/LoginDataSource.kt
  app/src/main/java/com/sweven/blockcovid/data/LoginRepository.kt
  app/src/main/java/com/sweven/blockcovid/data/Result.kt
  app/src/main/java/com/sweven/blockcovid/services/ErrorBody.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoginActivity.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoginResult.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoginViewModel.kt
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: improvement

#26 Feature/userpage
  .github/workflows/build-app.yml
  app/build.gradle
  app/src/androidTest/java/com/sweven/blockcovid/FullRunTest.kt
  app/src/main/java/com/sweven/blockcovid/InputChecks.kt
  app/src/main/java/com/sweven/blockcovid/MainActivity.kt
  app/src/main/java/com/sweven/blockcovid/StartActivity.kt
  app/src/main/java/com/sweven/blockcovid/data/LoginRepository.kt
  app/src/main/java/com/sweven/blockcovid/services/APIChangePassword.kt
  app/src/main/java/com/sweven/blockcovid/services/gsonReceive/ErrorBody.kt
  app/src/main/java/com/sweven/blockcovid/ui/account/AccountFragment.kt
  app/src/main/java/com/sweven/blockcovid/ui/account/AccountViewModel.kt
  app/src/main/java/com/sweven/blockcovid/ui/changePassword/ChangePasswordFormState.kt
  app/src/main/java/com/sweven/blockcovid/ui/changePassword/ChangePasswordFragment.kt
  app/src/main/java/com/sweven/blockcovid/ui/changePassword/ChangePasswordViewModel.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoggedInUserView.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoginActivity.kt
  app/src/main/java/com/sweven/blockcovid/ui/login/LoginViewModel.kt
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_change_password.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_reservation.xml
  app/src/main/res/layout/fragment_room1.xml
  app/src/main/res/layout/fragment_room2.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/raw/crt.pem
  app/src/main/res/raw/key.pem
  app/src/main/res/raw/sweven.p12
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/sweven/blockcovid/InputChecksTest.kt
  build.gradle
Labels: enhancement
